
from generalpackager.api.localrepo.base.target import _LocalRepo_Target

from itertools import chain


class Packages(_LocalRepo_Target.Targets):
    """ Stores all general packages, meant to be generated by workflows.
        Manual for now to see if it's a good solution. """
    python = [
        "generallibrary",
        "generalfile",
        "generalvector",
        "generalgui",
        "generalbrowser",
        "generalmainframe",
        "generalpackager",
    ]
    node = [
        "genlibrary",
        "genvector",
    ]
    django = []
    exe = []

    @classmethod
    def all_packages(cls):
        return list(chain(*cls.field_values_defaults()))

