

class PackageHostProtocol:
    def download(self, path=None, version=None, overwrite=False): ...
    def url(self): ...
    def exists(self): ...
    def get_owners_packages(self): ...
    def get_version(self): ...
    def get_date(self): ...


class LocalRepoProtocol:
    def install(self, local=True, editable=False): ...
    def uninstall(self, local=True, editable=False): ...
    def run_tests(self): ...
    def publish(self, public=True): ...
