""" Not using typing.Protocol because that's for type checking only.
    Not using abc because I don't want to define an extra metaclass.
        The only thing that'd be nice is if """

class PackageHostProtocol:
    """ GitHub.com, PyPI.org, NPMjs.com"""
    def download(self, path=None, version=None, overwrite=False): ...
    def url(self): ...
    def exists(self): ...
    def get_owners_packages(self): ...
    def get_version(self): ...
    def get_date(self): ...


class LocalRepoProtocol:
    """ Python and Node target. """
    def install(self, local=True, editable=False): ...
    def uninstall(self, local=True, editable=False): ...
    def run_tests(self): ...
    def publish(self, public=True): ...

    def list_packages(self, local=True, editable=None) -> list[str]: ...

