name: workflow
on:
  push:
    branches:
      - master
jobs:
  unittest:
    if: contains(github.event.head_commit.message, '[CI NOTEST]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install necessities pip, setuptools, wheel, twine
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Install git repos ManderaGeneral/generallibrary
        run: pip install git+https://github.com/ManderaGeneral/generallibrary.git
      - name: Install git repos ManderaGeneral/generalfile
        run: pip install git+https://github.com/ManderaGeneral/generalfile.git
      - name: Install git repos ManderaGeneral/generalvector
        run: pip install git+https://github.com/ManderaGeneral/generalvector.git
      - name: Install git repos ManderaGeneral/generalgui
        run: pip install git+https://github.com/ManderaGeneral/generalgui.git
      - name: Install git repos ManderaGeneral/generalpackager
        run: pip install git+https://github.com/ManderaGeneral/generalpackager.git
      - name: Clone all repos
        run: python -c "from generalpackager import Packager; packager = Packager('generalpackager', ''); packager.load_general_packagers(); print(packager.get_ordered_names())"
        env:
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          PACKAGER_GITHUB_API: ${{ secrets.PACKAGER_GITHUB_API }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
