name: workflow
on:
  push:
    branches:
      - master
jobs:
  unittest:
    if: contains(github.event.head_commit.message, '[CI NOTEST]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install necessities pip, wheel and twine
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - name: Install git repos ManderaGeneral/generalpackager
        run: |
          pip install git+https://github.com/ManderaGeneral/generalpackager.git
      - name: Clone all repos
        run: python -c "from generalpackager import PackagerGrp; grp = PackagerGrp(); print(grp.packagers)"
        env:
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          PACKAGER_GITHUB_API: ${{ secrets.PACKAGER_GITHUB_API }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
